# Generated by Django 4.2.7 on 2024-01-14 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='detail_text',
            field=models.TextField(max_length=10000, verbose_name='Description'),
        ),
    ]
